

DROP TABLE administrador CASCADE CONSTRAINTS;

DROP TABLE asistencia CASCADE CONSTRAINTS;

DROP TABLE blindaje CASCADE CONSTRAINTS;

DROP TABLE caracteristica_lugar CASCADE CONSTRAINTS;

DROP TABLE caracteristica_via CASCADE CONSTRAINTS;

DROP TABLE comparendo CASCADE CONSTRAINTS;

DROP TABLE curso CASCADE CONSTRAINTS;

DROP TABLE detalle_comparendo CASCADE CONSTRAINTS;

DROP TABLE empresa CASCADE CONSTRAINTS;

DROP TABLE examen CASCADE CONSTRAINTS;

DROP TABLE grua CASCADE CONSTRAINTS;

DROP TABLE historial_dueno CASCADE CONSTRAINTS;

DROP TABLE informe_accidente_transito CASCADE CONSTRAINTS;

DROP TABLE licencia CASCADE CONSTRAINTS;

DROP TABLE lugar CASCADE CONSTRAINTS;

DROP TABLE municipio CASCADE CONSTRAINTS;

DROP TABLE pago_comparendo CASCADE CONSTRAINTS;

DROP TABLE perjudicados CASCADE CONSTRAINTS;

DROP TABLE persona CASCADE CONSTRAINTS;

DROP TABLE poliza_seguro CASCADE CONSTRAINTS;

DROP TABLE requisitos CASCADE CONSTRAINTS;

DROP TABLE testigos CASCADE CONSTRAINTS;

DROP TABLE tipo_carroceria CASCADE CONSTRAINTS;

DROP TABLE tipo_infraccion CASCADE CONSTRAINTS;

DROP TABLE tipo_tramite CASCADE CONSTRAINTS;

DROP TABLE tramite CASCADE CONSTRAINTS;

DROP TABLE usuario CASCADE CONSTRAINTS;

DROP TABLE validacion CASCADE CONSTRAINTS;

DROP TABLE valores CASCADE CONSTRAINTS;

DROP TABLE vehiculo CASCADE CONSTRAINTS;

DROP TABLE vehiculo_tramite CASCADE CONSTRAINTS;

DROP TABLE vehiculos_afectados CASCADE CONSTRAINTS;

DROP TABLE tipo_documento CASCADE CONSTRAINTS;


CREATE TABLE administrador (
    id           INTEGER NOT NULL,
    usuario      VARCHAR2(20 CHAR) NOT NULL,
    contrasena   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE administrador ADD CONSTRAINT administrador_pk PRIMARY KEY ( id );

CREATE TABLE asistencia (
    id         INTEGER NOT NULL,
    curso_id   INTEGER NOT NULL
);

ALTER TABLE asistencia ADD CONSTRAINT asistencia_pk PRIMARY KEY ( id );


CREATE TABLE blindaje (
    numero_resolucion   INTEGER NOT NULL,
    fecha               DATE
);

ALTER TABLE blindaje ADD CONSTRAINT blindaje_pk PRIMARY KEY ( numero_resolucion );

CREATE TABLE caracteristica_lugar (
    id           INTEGER NOT NULL,
    area_id      VARCHAR2(20 CHAR) NOT NULL,
    sector_id    VARCHAR2(20 CHAR) NOT NULL,
    zona_id      VARCHAR2(20 CHAR) NOT NULL,
    disenio_id   VARCHAR2(20 CHAR) NOT NULL,
    tiempo_id    VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE caracteristica_lugar ADD CONSTRAINT caracteristica_lugar_pk PRIMARY KEY ( id );


CREATE TABLE caracteristica_via (
    id                       INTEGER NOT NULL,
    carac_geometrica_via_1   VARCHAR2(10 CHAR) NOT NULL,
    carac_geometrica_via_2   VARCHAR2(10 CHAR) NOT NULL,
    carac_geometrica_via_3   VARCHAR2(10 CHAR) NOT NULL,
    utilizacion              VARCHAR2(20 CHAR) NOT NULL,
    calzada                  VARCHAR2(20 CHAR) NOT NULL,
    carril                   VARCHAR2(20 CHAR) NOT NULL,
    material                 VARCHAR2(20 CHAR) NOT NULL,
    estado                   VARCHAR2(20 CHAR) NOT NULL,
    condicion                VARCHAR2(20 CHAR),
    iluminacion              VARCHAR2(20 CHAR) NOT NULL,
    disminucion_visual       VARCHAR2(20 CHAR) NOT NULL,
    control_semaforo         VARCHAR2(20 CHAR) NOT NULL,
    control_senales          VARCHAR2(5 CHAR) NOT NULL,
    control_demarcacion      VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE caracteristica_via ADD CONSTRAINT caracteristicas_via_pk PRIMARY KEY ( id );


CREATE TABLE comparendo (
    id                       INTEGER NOT NULL,
    fecha                    DATE NOT NULL,
    localidad_comuna         VARCHAR2(20 CHAR) NOT NULL,
    via_principal            VARCHAR2(50 CHAR) NOT NULL,
    via_secundaria           VARCHAR2(50 CHAR) NOT NULL,
    modalidad_transporte     VARCHAR2(50 CHAR) NOT NULL,
    radio_accion             VARCHAR2(20 CHAR) NOT NULL,
    tipo_infractor           VARCHAR2(20 CHAR) NOT NULL,
    descripcion              VARCHAR2(100 CHAR) NOT NULL,
    vehiculo_placa           VARCHAR2(20 CHAR) NOT NULL,
    estado                   VARCHAR2(30 CHAR) NOT NULL,
    municipio_id             INTEGER NOT NULL,
    grua_id                  INTEGER,
    tipo_infraccion_codigo   VARCHAR2(10 CHAR) NOT NULL,
    infractor                VARCHAR2(20 CHAR) NOT NULL,
    agente                   VARCHAR2(20 CHAR) NOT NULL,
    testigo                  VARCHAR2(20 CHAR)
);

ALTER TABLE comparendo ADD CONSTRAINT comparendo_pk PRIMARY KEY ( id );


CREATE TABLE curso (
    id                  INTEGER NOT NULL,
    docente             VARCHAR2(20 CHAR) NOT NULL,
    fecha               DATE,
    hora_inicio         VARCHAR2(10 CHAR),
    hora_finalizacion   VARCHAR2(10 CHAR)
);

ALTER TABLE curso ADD CONSTRAINT curso_pk PRIMARY KEY ( id );

CREATE TABLE detalle_comparendo (
    id                       INTEGER NOT NULL,
    aceptacion_compatrendo   INTEGER NOT NULL,
    fecha_asistencia         DATE
);

ALTER TABLE detalle_comparendo ADD CONSTRAINT detalle_comparendo_pk PRIMARY KEY ( id );


CREATE TABLE empresa (
    nit      INTEGER NOT NULL,
    nombre   VARCHAR2(20) NOT NULL
);

ALTER TABLE empresa ADD CONSTRAINT empresav1_pkv1 PRIMARY KEY ( nit );

CREATE TABLE examen(
    id                     INTEGER NOT NULL,
    examen_embriaguez      VARCHAR2(20 CHAR),
    examen_droga           VARCHAR2(20 CHAR),
    grado_examen_droga     VARCHAR2(10 CHAR),
    grado_examen_alcohol   VARCHAR2(10 CHAR)
);

ALTER TABLE examen ADD CONSTRAINT examen_pk PRIMARY KEY ( id );

CREATE TABLE grua (
    numero_grua                INTEGER NOT NULL,
    placa                      VARCHAR2(10) NOT NULL,
    consecutivo                VARCHAR2(20) NOT NULL,
    direccion_patio_asignado   VARCHAR2(20 CHAR)
);

ALTER TABLE grua ADD CONSTRAINT grua_pk PRIMARY KEY ( numero_grua );

ALTER TABLE grua ADD CONSTRAINT grua__un UNIQUE ( placa );

CREATE TABLE historial_dueno (
    id               INTEGER,
    vehiculo_placa   VARCHAR2(20 CHAR) NOT NULL,
    fecha            DATE,
    persona_nip      VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE historial_dueno ADD CONSTRAINT historial_dueno_pk PRIMARY KEY ( id );

CREATE TABLE informe_accidente_transito (
    id                INTEGER NOT NULL,
    tipo_gravedad     VARCHAR2(20 CHAR) NOT NULL,
    fecha_hora        DATE NOT NULL,
    clase_accidente   VARCHAR2(20 CHAR) NOT NULL,
    choque_con        VARCHAR2(20 CHAR) NOT NULL,
    objeto_fijo       VARCHAR2(20 CHAR) NOT NULL,
    croquis           BLOB,
    numero_muertos    INTEGER NOT NULL,
    numero_heridos    INTEGER NOT NULL,
    agente            VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE informe_accidente_transito ADD CONSTRAINT informe_accidente_transito_pk PRIMARY KEY ( id );

CREATE TABLE licencia (
    persona              VARCHAR2(20 CHAR) NOT NULL,
    numero_licencia      VARCHAR2(20) NOT NULL,
    fecha_expedicion     DATE,
    fecha_vencimiento    DATE,
    oficina_transito     VARCHAR2(20),
    categoria_licencia   VARCHAR2(50 CHAR)
);

ALTER TABLE licencia ADD CONSTRAINT licencia_pk PRIMARY KEY ( persona );

ALTER TABLE licencia ADD CONSTRAINT licencia_persona__un UNIQUE ( numero_licencia );

CREATE TABLE lugar (
    id                 INTEGER NOT NULL,
    coordenanda_x      VARCHAR2(5 CHAR),
    coordenada_y       VARCHAR2(5 CHAR),
    direccion          VARCHAR2(50 CHAR) NOT NULL,
    localidad_comuna   VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE lugar ADD CONSTRAINT lugar_pk PRIMARY KEY ( id );


CREATE TABLE municipio (
    id       INTEGER NOT NULL,
    nombre   VARCHAR2(20) NOT NULL
);

ALTER TABLE municipio ADD CONSTRAINT municipiov1_pk PRIMARY KEY ( id );

CREATE TABLE tipo_documento (
    id       INTEGER NOT NULL,
    nombre   VARCHAR2(50) NOT NULL
);

ALTER TABLE tipo_documento ADD CONSTRAINT tipo_documento_pk PRIMARY KEY ( id );

CREATE TABLE pago_comparendo (
    id              INTEGER NOT NULL,
    interese_mora   INTEGER,
    monto_total     INTEGER
);

ALTER TABLE pago_comparendo ADD CONSTRAINT pago_comparendo_pk PRIMARY KEY ( id );

CREATE TABLE perjudicados (
    id                       INTEGER NOT NULL,
    tipo_perjudicado         VARCHAR2(20 CHAR),
    vehiculos_afectados_id   INTEGER NOT NULL,
    cinturon                 CHAR(1),
    casco                    CHAR(1),
    sexo                     VARCHAR2(10 CHAR),
    gravedad                 VARCHAR2(10 CHAR),
    condicion                VARCHAR2(10 CHAR),
    persona_nip              VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE perjudicados ADD CONSTRAINT perjudicados_pk PRIMARY KEY ( id );


CREATE TABLE persona (
    nip                VARCHAR2(20 CHAR) NOT NULL,
    nombre_completo    VARCHAR2(50 CHAR) NOT NULL,
    fecha_nacimiento   DATE NOT NULL,
    direccion          VARCHAR2(100 CHAR) NOT NULL,
    eps                VARCHAR2(20 CHAR) NOT NULL,
    tipo_documento     INTEGER NOT NULL,
    municipio_id       INTEGER NOT NULL,
    telefono           VARCHAR2(20 CHAR) NOT NULL,
    placa_agente       INTEGER
);

ALTER TABLE persona ADD CONSTRAINT persona_pk PRIMARY KEY ( nip );

ALTER TABLE persona ADD CONSTRAINT persona__un UNIQUE ( placa_agente );


CREATE TABLE poliza_seguro (
    n_poliza               VARCHAR2(20 CHAR) NOT NULL,
    fecha_vencimiento      DATE NOT NULL,
    compania_aseguradora   VARCHAR2(20 CHAR),
    placa                  VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE poliza_seguro ADD CONSTRAINT poliza_seguro_pkv1 PRIMARY KEY ( placa );


CREATE TABLE requisitos (
    id                INTEGER NOT NULL,
    descripcion       VARCHAR2(500 CHAR),
    tipo_tramite_id   INTEGER NOT NULL
);

ALTER TABLE requisitos ADD CONSTRAINT requisitos_pk PRIMARY KEY ( id );


CREATE TABLE testigos (
    id                              INTEGER NOT NULL,
    informe_accidente_transito_id   INTEGER NOT NULL,
    testimonio                      VARCHAR2(100 CHAR),
    persona_nip                     VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE testigos ADD CONSTRAINT testigos_pk PRIMARY KEY ( id );


CREATE TABLE tipo_carroceria (
    codigo   INTEGER NOT NULL,
    tipo     VARCHAR2(20 CHAR)
);

ALTER TABLE tipo_carroceria ADD CONSTRAINT tipo_carroceria_pk PRIMARY KEY ( codigo );

CREATE TABLE tipo_infraccion (
    codigo                VARCHAR2(10 CHAR) NOT NULL,
    inmovilizacion        INTEGER NOT NULL,
    suspencion_licencia   INTEGER NOT NULL,
    salarios_minimos      INTEGER NOT NULL,
    descripcion           VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE tipo_infraccion ADD CONSTRAINT infraccion_pk PRIMARY KEY ( codigo );

CREATE TABLE tipo_tramite (
    id            INTEGER NOT NULL,
    descripcion   VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE tipo_tramite ADD CONSTRAINT tipo_tramite_pk PRIMARY KEY ( id );


CREATE TABLE tramite (
    id                    INTEGER NOT NULL,
    fecha                 DATE,
    descripcion           VARCHAR2(50 CHAR),
    valor                 INTEGER NOT NULL,
    vehiculo_tramite_id   VARCHAR2(20 CHAR) NOT NULL,
    tipo_tramite_id       INTEGER NOT NULL,
    persona_nip           VARCHAR2(20 CHAR)NOT NULL,
    receptor              VARCHAR2(20 CHAR)
);

ALTER TABLE tramite ADD CONSTRAINT tramite_pk PRIMARY KEY ( id );


CREATE TABLE usuario (
    nombre_usuario        VARCHAR2(20 CHAR) NOT NULL,
    password              VARCHAR2(20 CHAR) NOT NULL,
    email                 VARCHAR2(50 CHAR) DEFAULT 'No se especifico E-Mail',
    respuesta_seguridad   VARCHAR2(50 CHAR) NOT NULL,
    tipo_usuario          VARCHAR2(20 CHAR) NOT NULL,
    validacion_id         INTEGER NOT NULL,
    persona_nip           VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( nombre_usuario );

ALTER TABLE usuario ADD CONSTRAINT tipo_usuario_nip__un UNIQUE ( persona_nip,tipo_usuario );

CREATE TABLE validacion (
    id            INTEGER NOT NULL,
    descripcion   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE validacion ADD CONSTRAINT validacion_pk PRIMARY KEY ( id );


CREATE TABLE valores (
    fecha                  DATE NOT NULL,
    valor_salario_minimo   INTEGER NOT NULL,
    valor_dia_mora         INTEGER,
    descuento_comparendo   INTEGER,
    dias_habiles           INTEGER
);

ALTER TABLE valores ADD CONSTRAINT valores_pk PRIMARY KEY ( fecha );


CREATE TABLE vehiculo (
    placa                  VARCHAR2(20 CHAR) NOT NULL,
    modelo                 VARCHAR2(20 CHAR),
    linea                  VARCHAR2(20 CHAR),
    marca                  VARCHAR2(20 CHAR),
    licencia_transito      VARCHAR2(20 CHAR),
    clase_vehiculo         VARCHAR2(20 CHAR),
    tipo_vehiculo          VARCHAR2(20 CHAR),
    lugar_matricula        VARCHAR2(20 CHAR),
    nacionalidad           VARCHAR2(20 CHAR),
    color                  VARCHAR2(20 CHAR),
    empresa_nit            INTEGER,
    capacidad_carga        INTEGER,
    numero_pasajeros       INTEGER,
    no_targeta_operacion   INTEGER
);

ALTER TABLE vehiculo ADD CONSTRAINT vehiculov1_pk PRIMARY KEY ( placa );

ALTER TABLE vehiculo ADD CONSTRAINT vehiculo__un UNIQUE ( placa,licencia_transito );


CREATE TABLE vehiculo_tramite (
    placa                        VARCHAR2(20 CHAR) NOT NULL,
    combustible                  VARCHAR2(20 CHAR),
    clindrada                    VARCHAR2(20 CHAR),
    no_motor                     INTEGER,
    no_chasis                    INTEGER,
    no_serie                     INTEGER,
    no_vin                       INTEGER,
    blindaje_numero_resolucion   INTEGER,
    tipo_carroceria_codigo       INTEGER
);

ALTER TABLE vehiculo_tramite ADD CONSTRAINT vehiculo_comparendo_pk PRIMARY KEY ( placa );


CREATE TABLE vehiculos_afectados (
    id                              INTEGER NOT NULL,
    vehiculo_placa                  VARCHAR2(20 CHAR) NOT NULL,
    inmovilizacion                  VARCHAR2(20 CHAR),
    disposicion                     VARCHAR2(20 CHAR),
    prpietario_mismo_conductor      CHAR(1),
    informe_accidente_transito_id   INTEGER NOT NULL,
    falla_en                        VARCHAR2(20 CHAR),
    lugar_impacto                   VARCHAR2(50 CHAR),
    version                         VARCHAR2(50 CHAR)
);

ALTER TABLE vehiculos_afectados ADD CONSTRAINT vehiculos_afectados_pk PRIMARY KEY ( id );


ALTER TABLE comparendo
    ADD CONSTRAINT agente FOREIGN KEY ( agente )
        REFERENCES persona ( nip );

ALTER TABLE asistencia
    ADD CONSTRAINT asistencia_curso_fk FOREIGN KEY ( curso_id )
        REFERENCES curso ( id );

ALTER TABLE asistencia
    ADD CONSTRAINT asistencia_detalle_c_fk FOREIGN KEY ( id )
        REFERENCES detalle_comparendo ( id );

ALTER TABLE caracteristica_lugar
    ADD CONSTRAINT c_l_i_a_t_fk FOREIGN KEY ( id )
        REFERENCES informe_accidente_transito ( id );

ALTER TABLE caracteristica_via
    ADD CONSTRAINT c_v_in_a_t_fk FOREIGN KEY ( id )
        REFERENCES informe_accidente_transito ( id );

ALTER TABLE comparendo
    ADD CONSTRAINT comparendo_grua_fk FOREIGN KEY ( grua_id )
        REFERENCES grua ( numero_grua );

ALTER TABLE comparendo
    ADD CONSTRAINT comparendo_infraccion_fk FOREIGN KEY ( tipo_infraccion_codigo )
        REFERENCES tipo_infraccion ( codigo );

ALTER TABLE comparendo
    ADD CONSTRAINT comparendo_vehiculo_fk FOREIGN KEY ( vehiculo_placa )
        REFERENCES vehiculo ( placa );

ALTER TABLE detalle_comparendo
    ADD CONSTRAINT d_c_c_fk FOREIGN KEY ( id )
        REFERENCES comparendo ( id );

ALTER TABLE examen
    ADD CONSTRAINT examen_perjudicados_fk FOREIGN KEY ( id )
        REFERENCES perjudicados ( id );

ALTER TABLE historial_dueno
    ADD CONSTRAINT h_d_pe_fk FOREIGN KEY ( persona_nip )
        REFERENCES persona ( nip );

ALTER TABLE historial_dueno
    ADD CONSTRAINT h_d_v_fk FOREIGN KEY ( vehiculo_placa )
        REFERENCES vehiculo ( placa );

ALTER TABLE informe_accidente_transito
    ADD CONSTRAINT in_a_t_p_fk FOREIGN KEY ( agente )
        REFERENCES persona ( nip );

ALTER TABLE lugar
    ADD CONSTRAINT l_i_ac_tr_fk FOREIGN KEY ( id )
        REFERENCES informe_accidente_transito ( id );

ALTER TABLE licencia
    ADD CONSTRAINT licencia_persona_fk FOREIGN KEY ( persona )
        REFERENCES persona ( nip );

ALTER TABLE comparendo
    ADD CONSTRAINT municipio FOREIGN KEY ( municipio_id )
        REFERENCES municipio ( id );

ALTER TABLE pago_comparendo
    ADD CONSTRAINT p_c_d_c_fk FOREIGN KEY ( id )
        REFERENCES detalle_comparendo ( id );

ALTER TABLE perjudicados
    ADD CONSTRAINT pe_v_a_fk FOREIGN KEY ( vehiculos_afectados_id )
        REFERENCES vehiculos_afectados ( id );

ALTER TABLE perjudicados
    ADD CONSTRAINT perjudicados_p_fk FOREIGN KEY ( persona_nip )
        REFERENCES persona ( nip );

ALTER TABLE comparendo
    ADD CONSTRAINT persona FOREIGN KEY ( infractor )
        REFERENCES persona ( nip );

ALTER TABLE persona
    ADD CONSTRAINT persona_municipio_fk FOREIGN KEY ( municipio_id )
        REFERENCES municipio ( id );
        
ALTER TABLE persona
    ADD CONSTRAINT persona_tipo_documento_fk FOREIGN KEY ( tipo_documento )
        REFERENCES tipo_documento ( id );

ALTER TABLE poliza_seguro
    ADD CONSTRAINT poliza_seguro_vehiculo_fk FOREIGN KEY ( placa )
        REFERENCES vehiculo ( placa );

ALTER TABLE requisitos
    ADD CONSTRAINT r_t_t_fk FOREIGN KEY ( tipo_tramite_id )
        REFERENCES tipo_tramite ( id );

ALTER TABLE testigos
    ADD CONSTRAINT t_in_a_t_fk FOREIGN KEY ( informe_accidente_transito_id )
        REFERENCES informe_accidente_transito ( id );

ALTER TABLE comparendo
    ADD CONSTRAINT testigo FOREIGN KEY ( testigo )
        REFERENCES persona ( nip );

ALTER TABLE testigos
    ADD CONSTRAINT testigos_persona_fk FOREIGN KEY ( persona_nip )
        REFERENCES persona ( nip );

ALTER TABLE tramite
    ADD CONSTRAINT tramite_tipo_tramite_fk FOREIGN KEY ( tipo_tramite_id )
        REFERENCES tipo_tramite ( id );
        
ALTER TABLE tramite
    ADD CONSTRAINT tramite_persona_fk FOREIGN KEY ( receptor )
        REFERENCES persona ( nip );

ALTER TABLE tramite
    ADD CONSTRAINT tramite_vehiculo_tramite_fk FOREIGN KEY ( vehiculo_tramite_id )
        REFERENCES vehiculo_tramite ( placa );

ALTER TABLE tramite
    ADD CONSTRAINT traspaso_persona FOREIGN KEY ( persona_nip )
        REFERENCES persona ( nip );

ALTER TABLE usuario
    ADD CONSTRAINT usuario_persona_fk FOREIGN KEY ( persona_nip )
        REFERENCES persona ( nip )
            ON DELETE CASCADE;

ALTER TABLE usuario
    ADD CONSTRAINT usuario_validacion_fk FOREIGN KEY ( validacion_id )
        REFERENCES validacion ( id );

ALTER TABLE vehiculos_afectados
    ADD CONSTRAINT v_a_i_a_t_fk FOREIGN KEY ( informe_accidente_transito_id )
        REFERENCES informe_accidente_transito ( id );

ALTER TABLE vehiculos_afectados
    ADD CONSTRAINT v_a_v_fk FOREIGN KEY ( vehiculo_placa )
        REFERENCES vehiculo ( placa );

ALTER TABLE vehiculo_tramite
    ADD CONSTRAINT v_t_b_fk FOREIGN KEY ( blindaje_numero_resolucion )
        REFERENCES blindaje ( numero_resolucion );

ALTER TABLE vehiculo_tramite
    ADD CONSTRAINT v_t_t_c_fk FOREIGN KEY ( tipo_carroceria_codigo )
        REFERENCES tipo_carroceria ( codigo );

ALTER TABLE vehiculo_tramite
    ADD CONSTRAINT v_t_v_fk FOREIGN KEY ( placa )
        REFERENCES vehiculo ( placa );

ALTER TABLE vehiculo
    ADD CONSTRAINT vehiculo_empresa_fk FOREIGN KEY ( empresa_nit )
        REFERENCES empresa ( nit );
             

--Insert en las tablas

INSERT INTO "TIPO_DOCUMENTO" (ID, NOMBRE) VALUES ('1', 'Cedula de ciudadania');
INSERT INTO "TIPO_DOCUMENTO" (ID, NOMBRE) VALUES ('2', 'Tarjeta de identidad');
INSERT INTO "TIPO_DOCUMENTO" (ID, NOMBRE) VALUES ('3', 'Cedula de extranjeria');
INSERT INTO "TIPO_DOCUMENTO" (ID, NOMBRE) VALUES ('4', 'Pasaporte');
INSERT INTO "TIPO_DOCUMENTO" (ID, NOMBRE) VALUES ('5', 'Registro civil');

INSERT INTO ADMINISTRADOR(ID, USUARIO,CONTRASENA)
VALUES(1,'admin','123');

INSERT INTO "VALIDACION" (ID, DESCRIPCION) VALUES (1,'Cual es su fecha de nacimiento?');
INSERT INTO "VALIDACION" (ID, DESCRIPCION) VALUES (2,'Cual es el nombre de su primer maestro?');
INSERT INTO "VALIDACION" (ID, DESCRIPCION) VALUES (3,'A que colegio de bachillerato asisti?');
INSERT INTO "VALIDACION" (ID, DESCRIPCION) VALUES (4,'Cual es el nombre de mi primera mascota?');
INSERT INTO "VALIDACION" (ID, DESCRIPCION) VALUES (5,'Cual es el nombre del hospital donde naci?');

INSERT INTO "MUNICIPIO" (ID, NOMBRE) VALUES ('1', 'Armenia');
INSERT INTO "MUNICIPIO" (ID, NOMBRE) VALUES ('2', 'Calarca');
INSERT INTO "MUNICIPIO" (ID, NOMBRE) VALUES ('3', 'Buenavista');
INSERT INTO "MUNICIPIO" (ID, NOMBRE) VALUES ('4', 'Circasia');

INSERT INTO PERSONA (NIP, NOMBRE_COMPLETO, FECHA_NACIMIENTO, DIRECCION, EPS, TIPO_DOCUMENTO, MUNICIPIO_ID, TELEFONO, PLACA_AGENTE)
VALUES('1095489585','ISABEL DAVILA GARZON',TO_DATE('1989/12/09','YYYY/MM/DD'),'CRA 5 # 24-12','COOMEVA',1,1,'310293023',190);

INSERT INTO PERSONA (NIP, NOMBRE_COMPLETO, FECHA_NACIMIENTO, DIRECCION, EPS, TIPO_DOCUMENTO, MUNICIPIO_ID, TELEFONO, PLACA_AGENTE)
VALUES('7475129','ANA MARIA OSPINA CARVAJAL',TO_DATE('1989/12/09','YYYY/MM/DD'),'CLL 2 # 10-21','SANIDAD',1,1,'2124503',234);

INSERT INTO PERSONA (NIP, NOMBRE_COMPLETO, FECHA_NACIMIENTO, DIRECCION, EPS, TIPO_DOCUMENTO, MUNICIPIO_ID, TELEFONO, PLACA_AGENTE)
VALUES('5482637','JACOB CANDELA ROMERO',TO_DATE('1989/12/09','YYYY/MM/DD'),'CRA 14N # 10-25','MEDIMAS',1,2,'3208439844',NULL);

INSERT INTO PERSONA (NIP, NOMBRE_COMPLETO, FECHA_NACIMIENTO, DIRECCION, EPS, TIPO_DOCUMENTO, MUNICIPIO_ID, TELEFONO, PLACA_AGENTE)
VALUES('1023954758','SERGIO LOPERA CARDENAS',TO_DATE('1989/12/09','YYYY/MM/DD'),'CLL 20N # 21-1','CONFAMILIAR',1,2,'213048348',NULL);

INSERT INTO USUARIO(NOMBRE_USUARIO,PASSWORD,EMAIL,RESPUESTA_SEGURIDAD,TIPO_USUARIO,VALIDACION_ID,PERSONA_NIP)
VALUES('ANMAOS','12345A.','ANAMARIA123@GMAIL.COM','1965/12/29','AGENTE',1,'7475129');

INSERT INTO USUARIO(NOMBRE_USUARIO,PASSWORD,EMAIL,RESPUESTA_SEGURIDAD,TIPO_USUARIO,VALIDACION_ID,PERSONA_NIP)
VALUES('ISDAGA','ISDAGAOD123.','GARZON10382@OUTLOOK.COM','MARIANA CARVAJAL','AGENTE',2,'1095489585');

INSERT INTO USUARIO(NOMBRE_USUARIO,PASSWORD,EMAIL,RESPUESTA_SEGURIDAD,TIPO_USUARIO,VALIDACION_ID,PERSONA_NIP)
VALUES('SELOCAR','SERGIO132.','SERGI13@HOTMAIL.COM','JORGE LACOSTA','FUNCIONARIO',2,'1023954758');

INSERT INTO USUARIO(NOMBRE_USUARIO,PASSWORD,EMAIL,RESPUESTA_SEGURIDAD,TIPO_USUARIO,VALIDACION_ID,PERSONA_NIP)
VALUES('JACARO','BEIBI13.','JACOBCARO19@GMAIL.COM','1970/10/07','CIUDADANO',1,'5482637');

INSERT INTO EMPRESA(NIT, NOMBRE)
VALUES(348,'COOMOCAR');

INSERT INTO EMPRESA(NIT,NOMBRE)
VALUES(304,'COTRASNOVA');

INSERT INTO VEHICULO(PLACA,MODELO,LINEA,MARCA,LICENCIA_TRANSITO,CLASE_VEHICULO,TIPO_VEHICULO,LUGAR_MATRICULA,NACIONALIDAD,COLOR,EMPRESA_NIT,CAPACIDAD_CARGA,NUMERO_PASAJEROS,NO_TARGETA_OPERACION)
VALUES('VLH-130','2004','MAZDA 626','MAZDA','0500693','PUBLICO','CARRO','BOGOTA','COLOMBIANA','VERDE',348,360,6,10329483);

INSERT INTO VEHICULO(PLACA,MODELO,LINEA,MARCA,LICENCIA_TRANSITO,CLASE_VEHICULO,TIPO_VEHICULO,LUGAR_MATRICULA,NACIONALIDAD,COLOR,EMPRESA_NIT,CAPACIDAD_CARGA,NUMERO_PASAJEROS,NO_TARGETA_OPERACION)
VALUES('GRA-231','2006','CHEVROLET SPARK','CHEVROLET','1038294','PRIVADO','CARRO','LA TEBAIDA','COLOMBIANA','VERDE',NULL,360,6,0);

INSERT INTO VEHICULO(PLACA,MODELO,LINEA,MARCA,LICENCIA_TRANSITO,CLASE_VEHICULO,TIPO_VEHICULO,LUGAR_MATRICULA,NACIONALIDAD,COLOR,EMPRESA_NIT,CAPACIDAD_CARGA,NUMERO_PASAJEROS,NO_TARGETA_OPERACION)
VALUES('ULX-124','2016','AKT 125','AKT','0139237','PRIVADO','MOTO','BOGOTA','COLOMBIANA','VERDE',NULL,200,2,0);

INSERT INTO VEHICULO(PLACA,MODELO,LINEA,MARCA,LICENCIA_TRANSITO,CLASE_VEHICULO,TIPO_VEHICULO,LUGAR_MATRICULA,NACIONALIDAD,COLOR,EMPRESA_NIT,CAPACIDAD_CARGA,NUMERO_PASAJEROS,NO_TARGETA_OPERACION)
VALUES('AXV-666','2010','A3','AUDI','0602743','PUBLICO','CARRO','ARMENIA','COLOMBIANA','VERDE',304,450,6,10328394);


INSERT INTO HISTORIAL_DUENO(ID,VEHICULO_PLACA,FECHA,PERSONA_NIP)
VALUES(1,'VLH-130',TO_DATE('1989/12/09','YYYY/MM/DD'),'1095489585');

INSERT INTO HISTORIAL_DUENO(ID,VEHICULO_PLACA,FECHA,PERSONA_NIP)
VALUES(2,'ULX-124',TO_DATE('1989/12/09','YYYY/MM/DD'),'7475129');

INSERT INTO HISTORIAL_DUENO(ID,VEHICULO_PLACA,FECHA,PERSONA_NIP)
VALUES(3,'AXV-666',TO_DATE('1989/12/09','YYYY/MM/DD'),'5482637');

INSERT INTO HISTORIAL_DUENO(ID,VEHICULO_PLACA,FECHA,PERSONA_NIP)
VALUES(4,'GRA-231',TO_DATE('1989/12/09','YYYY/MM/DD'),'1023954758');

INSERT INTO BLINDAJE(NUMERO_RESOLUCION,FECHA)
VALUES(102,TO_DATE('1989/12/09','YYYY/MM/DD'));

INSERT INTO BLINDAJE(NUMERO_RESOLUCION,FECHA)
VALUES(104,TO_DATE('1989/12/09','YYYY/MM/DD'));

INSERT INTO TIPO_CARROCERIA(CODIGO, TIPO)
VALUES(112,'PUERTAS');

INSERT INTO TIPO_CARROCERIA(CODIGO, TIPO)
VALUES(113,'BAUL');

INSERT INTO VEHICULO_TRAMITE(PLACA,COMBUSTIBLE,CLINDRADA,NO_MOTOR,NO_CHASIS,NO_SERIE,NO_VIN,BLINDAJE_NUMERO_RESOLUCION,TIPO_CARROCERIA_CODIGO)
VALUES('VLH-130','DIESEL','193',2038,112,938,1042,102,112);

INSERT INTO VEHICULO_TRAMITE(PLACA,COMBUSTIBLE,CLINDRADA,NO_MOTOR,NO_CHASIS,NO_SERIE,NO_VIN,BLINDAJE_NUMERO_RESOLUCION,TIPO_CARROCERIA_CODIGO)
VALUES('ULX-124','GVN','329',1028,139,382,1403,104,113);

INSERT INTO VEHICULO_TRAMITE(PLACA,COMBUSTIBLE,CLINDRADA,NO_MOTOR,NO_CHASIS,NO_SERIE,NO_VIN,BLINDAJE_NUMERO_RESOLUCION,TIPO_CARROCERIA_CODIGO)
VALUES('AXV-666','EXTRA','234',0132,124,103,4039,102,113);

INSERT INTO VEHICULO_TRAMITE(PLACA,COMBUSTIBLE,CLINDRADA,NO_MOTOR,NO_CHASIS,NO_SERIE,NO_VIN,BLINDAJE_NUMERO_RESOLUCION,TIPO_CARROCERIA_CODIGO)
VALUES('GRA-231','GVN','345',1245,938,102,1394,104,112);

INSERT INTO TIPO_TRAMITE(ID,DESCRIPCION)
VALUES(1,'MATRICULA INICIAL');

INSERT INTO TIPO_TRAMITE(ID,DESCRIPCION)
VALUES(2,'TRANSPASO VEHICULAR');

INSERT INTO TIPO_TRAMITE(ID,DESCRIPCION)
VALUES(3,'INSCRIPCIONES DE PRENDAS');

INSERT INTO TIPO_TRAMITE(ID,DESCRIPCION)
VALUES(4,'CERTIFICADO DE TRADICION');

INSERT INTO TRAMITE(ID,FECHA,DESCRIPCION,VALOR,VEHICULO_TRAMITE_ID,TIPO_TRAMITE_ID,PERSONA_NIP,RECEPTOR)
VALUES(1,TO_DATE('1989/12/09','YYYY/MM/DD'),'PARA ESTAR A PAZ Y SALVO',1239,'GRA-231',3,'1023954758',NULL);

INSERT INTO TRAMITE(ID,FECHA,DESCRIPCION,VALOR,VEHICULO_TRAMITE_ID,TIPO_TRAMITE_ID,PERSONA_NIP,RECEPTOR)
VALUES(2,TO_DATE('1989/12/09','YYYY/MM/DD'),'QUIERO VENDER MI VEHICULO',1239234,'VLH-130',3,'5482637',NULL);

INSERT INTO REQUISITOS(ID,DESCRIPCION,TIPO_TRAMITE_ID)
VALUES(1,'ESTAR LIBRES DE DEUDAS CON RESPECTO AL VEHICULO',1);

INSERT INTO REQUISITOS(ID,DESCRIPCION,TIPO_TRAMITE_ID)
VALUES(2,'ESTAR LIBRES DE DEUDAS CON RESPECTO AL VEHICULO',2);

INSERT INTO REQUISITOS(ID,DESCRIPCION,TIPO_TRAMITE_ID)
VALUES(3,'ESTAR LIBRES DE DEUDAS CON RESPECTO AL VEHICULO',3);

INSERT INTO REQUISITOS(ID,DESCRIPCION,TIPO_TRAMITE_ID)
VALUES(4,'ESTAR LIBRES DE DEUDAS CON RESPECTO AL VEHICULO',4);

INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A01',0,0,4,'NO TRANSITAR POR LA DERECHA DE LA VIA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A02',0,0,4,'SUJETARSE DE OTRO VEHICULO EN CIRCULACION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A03',0,0,4,'TRANSPORTAR PERSONAS O COSAS QUE DISMINUYAN LA VISIBILIDAD E INCOMODEN LA CONDUCCION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A04',0,0,4,'TRANSITAR POR ANDENES Y DEMAS LUGARES DESTINADOS AL TRANSITO DE PEATONES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A05',0,0,4,'NO RESPETAR LAS SEÃ‘ALES DE TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A06',0,0,4,'TRANSITAR SIN LOS DISPOSITIVOS LUMINOSOS REQUERIDOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A07',0,0,4,'TRANSITAR SIN DISPOSITIVOS QUE PERMITAN PARADA INMEDIATA O CON ELLOS DEFECTUOSOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A08',0,0,4,'TRANSITAR POR ZONAS PROHIBIDAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A09',0,0,4,'ADELANTAR ENTRE DOS (2) VEHICULOS AUTOMOTORES QUE ESTEN EN SUS RESPECTIVOS CARRILES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A10',0,0,4,'CONDUCIR POR LA VIA FERREA O POR ZONAS DE PROTECCION Y SEGURIDAD');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A11',1,0,4,'TRANSITAR POR ZONAS RESTRINGIDAS O POR VIAS DE ALTA VELOCIDAD COMO AUTOPISTAS Y ARTERIAS EN ESTE CASO EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('A12',1,0,4,'PRESTAR SERVICIO PUBLICO CON ESTE TIPO DE VEHICULOS. ADEMAS EL VEHICULO SERA INMOVILIZADO POR PRIMERA VEZ POR EL TERMINO DE CINCO DIAS POR SEGUNDA VEZ VEINTE DIAS Y POR TERCERA VEZ CUARENTA DIA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B01',0,0,8,'CONDUCIR UN VEHICULO SIN LLEVAR CONSIGO LA LICENCIA DE CONDUCCION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B02',0,0,8,'CONDUCIR UN VEHICULO CON LA LICENCIA DE CONDUCCION VENCIDA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B03',0,0,8,'CONDUCIR UN VEHICULO SIN PLACAS O SIN EL PERMISO VIGENTE EXPEDIDO POR LA AUTORIDAD DE TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B04',0,0,8,'CONDUCIR UN VEHICULO CON PLACAS ADULTERADAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B05',0,0,8,'CONDUCIR UN VEHICULO CON UNA SOLA PLACA O SIN EL PERMISO VIGENTE EXPEDIDO POR AUTORIDAD DE TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B06',1,0,8,'CONDUCIR UN VEHICULO CON PLACAS FALSAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B07',1,0,8,'NO INFORMAR A LA AUTORIDAD DE TRANSITO COMPETENTE EL CAMBIO DE MOTOR O COLOR DE UN VEHICULO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B08',0,0,8,'NO PAGAR EL PEAJE EN LOS SITIOS ESTABLECIDOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B09',0,0,8,'UTILIZAR EQUIPOS DE SONIDO A UN VOLUMEN QUE INCOMODE A LOS PASAJEROS DE UN VEHICULO DE SERVICIO PUBLICO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B10',0,0,8,'CONDUCIR UN VEHICULO CON VIDRIOS POLARIZADOS ENTINTADOS U OSCURECIDOS SIN PORTAR EL PERMISO RESPECTIVO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B11',0,0,8,'CONDUCIR UN VEHICULO CON PROPAGANDA PUBLICIDAD O ADHESIVOS EN SUS VIDRIOS QUE OBSTACULICEN LA VISIBILIDAD');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B12',0,0,8,'NO RESPETAR LAS NORMAS ESTABLECIDAS POR LA AUTORIDAD COMPETENTE PARA EL TRANSITO DE CORTEJOS FUNEBRES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B13',0,0,8,'NO RESPETAR LAS FORMACIONES DE TROPAS LA MARCHA DE DESFILES PROCESIONES ENTIERROS FILAS ESTUDIANTILES Y MANIFESTACIONES PUBLICAS Y ACTIVIDADES DEPORTIVAS DEBIDAMENTE AUTORIZADAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B14',0,0,8,'REMOLCAR OTRO VEHICULO VIOLANDO LO DISPUESTO POR EL CODIGO NACIONAL DE TRANSITO TERRESTRE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B15',0,0,8,'CONDUCIR UN VEHICULO DE SERVICIO PUBLICO QUE NO LLEVE EL AVISO DE TARIFAS OFICIALES EN CONDICIONES DE FACIL LECTURA PARA LOS PASAJEROS O POSEER ESTE AVISO DETERIORADO O ADULTERADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B16',0,0,8,'PERMITIR QUE EN UN VEHICULO DE SERVICIO PUBLICO PARA TRANSPORTE DE PASAJEROS SE LLEVEN ANIMALES U OBJETOS QUE INCOMODEN A LOS PASAJEROS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B17',0,0,8,'ABANDONAR UN VEHICULO DE SERVICIO PUBLICO CON PASAJEROS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B18',0,0,8,'CONDUCIR UN VEHICULO DE SERVICIO PUBLICO INDIVIDUAL DE PASAJEROS SIN CUMPLIR CON LO ESTIPULADO EN EL CODIGO NACIONAL DE TRANSITO TERRESTRE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B19',0,0,8,'REALIZAR EL CARGUE O DESCARGUE DE UN VEHICULO EN SITIOS Y HORAS PROHIBIDAS POR LAS AUTORIDADES COMPETENTES DE ACUERDO CON LO ESTABLECIDO EN LAS NORMAS CORRESPONDIENTES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B20',0,0,8,'TRANSPORTAR CARNE, PESCADO O ALIMENTOS FACILMENTE CORRUPTIBLES EN VEHICULOS QUE NO CUMPLAN CON LAS CONDICIONES FIJADAS POR EL MINISTERIO DE TRANSPORTE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B21',0,0,8,'LAVAR VEHICULOS EN VIA PUBLICA RIOS CANALES QUEBRADAS ETC');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B22',0,0,8,'LLEVAR NIÃ‘OS MENORES DE 10 AÃ‘OS EN EL ASIENTO DELANTERO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('B23',0,0,8,'UTILIZAR RADIOS EQUIPOS DE SONIDO O DE AMPLIFICACION A UN VOLUMEN QUE SUPERE LOS DECIBELES MAXIMOS ESTABLECIDOS POR LAS AUTORIDADES AMBIENTALES. DE IGUAL MANERA UTILIZAR PANTALLAS PROYECTORES DE IMAGEN O SIMILARES MIENTRAS ESTE EN MOVIMIENTO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C01',1,0,15,'PRESENTAR LICENCIA DE CONDUCCION ADULTERADA O AJENA, LO CUAL DARA LUGAR A LA INMOVILIZACION DEL VEHICULO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C02',0,0,15,'ESTACIONAR UN VEHICULO EN SITIOS PROHIBIDOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C03',0,0,15,'BLOQUEAR UNA CALZADA O INTERSECCION CON UN VEHICULO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C04',0,0,15,'ESTACIONAR UN VEHICULO SIN TOMAR LAS DEBIDAS PRECAUCIONES O SIN COLOCAR A LA DISTANCIA SEÃ‘ALADA POR ESTE CODIGO LAS SEÃ‘ALES DE PELIGRO REGLAMENTARIAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C05',0,0,15,'NO REDUCIR LA VELOCIDAD SEGUN LO INDICADO POR ESTE CODIGO CUANDO TRANSITE POR UN CRUCE ESCOLAR EN LOS HORARIOS Y DIAS DE FUNCIONAMIENTO DE LA INSTITUCION EDUCATIVA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C06',0,0,15,'NO UTILIZAR EL CINTURON DE SEGURIDAD POR PARTE DE LOS OCUPANTES DEL VEHICULO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C07',0,0,15,'DEJAR DE SEÃ‘ALIZAR CON LAS LUCES DIRECCIONALES O MEDIANTE SEÃ‘ALES DE MANO Y CON LA DEBIDA ANTICIPACION LA MANIOBRA DE GIRO O DE CAMBIO DE CARRIL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C08',0,0,15,'TRANSITAR SIN LOS DISPOSITIVOS LUMINOSOS REQUERIDOS O SIN LOS ELEMENTOS DETERMINADOS EN EL CODIGO NACIONAL DE TRANSITO TERRESTRE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C09',0,0,15,'NO RESPETAR LAS SEÃ‘ALES DE DETENCION EN EL CRUCE DE UNA LINEA FERREA O CONDUCIR POR LA VIA FERREA O POR LAS ZONAS DE PROTECCION Y SEGURIDAD DE ELLA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C10',0,0,15,'CONDUCIR UN VEHICULO CON UNA O VARIAS PUERTAS ABIERTAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C11',0,0,15,'NO PORTAR EL EQUIPO DE PREVENCION Y SEGURIDAD ESTABLECIDO EN EL CODIGO NACIONAL DE TRANSITO TERRESTRE O EN LA REGLAMENTACION CORRESPONDIENTE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C12',0,0,15,'PROVEER DE COMBUSTIBLE UN VEHICULO AUTOMOTOR CON EL MOTOR ENCENDIDO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C13',0,0,15,'CONDUCIR UN VEHICULO AUTOMOTOR SIN LAS ADAPTACIONES PERTINENTES CUANDO EL CONDUCTOR PADECE UNA LIMITACION FISICA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C14',1,0,15,'TRANSITAR POR SITIOS RESTRINGIDOS O EN HORAS PROHIBIDAS POR LA AUTORIDAD COMPETENTE. ADEMAS DE HACERLO EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C15',0,0,15,'CONDUCIR UN VEHICULO PARTICULAR O DE SERVICIO PUBLICO EXCEDIENDO LA CAPACIDAD AUTORIZADA EN LA LICENCIA DE TRANSITO O TARJETA DE OPERACION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C16',0,0,15,'CONDUCIR UN VEHICULO ESCOLAR SIN EL PERMISO RESPECTIVO O LOS DISTINTIVOS REGLAMENTARIOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C17',0,0,15,'CIRCULAR CON COMBINACIONES DE VEHICULOS DE DOS (2) O MAS UNIDADES REMOLCADAS SIN AUTORIZACION ESPECIAL DE AUTORIDAD COMPETENTE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C18',0,0,15,'CONDUCIR UN VEHICULO AUTORIZADO PARA PRESTAR SERVICIO PUBLICO CON EL TAXIMETRO DAÃ‘ADO CON LOS SELLOS ROTOS O ETIQUETAS ADHESIVAS CON CALIBRACION VENCIDA O ADULTERADAS O CUANDO SE CAREZCA DE EL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C19',0,0,15,'DEJAR O RECOGER PASAJEROS EN SITIOS DISTINTOS DE LOS DEMARCADOS POR LAS AUTORIDADES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C20',1,0,15,'CONDUCIR UN VEHICULO DE CARGA EN EL QUE SE TRANSPORTEN MATERIALES DE CONSTRUCCION O A GRANEL SIN LAS MEDIDAS DE PROTECCION HIGIENE Y SEGURIDAD ORDENADAS. ADEMAS EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C21',1,0,15,'NO ASEGURAR LA CARGA PARA EVITAR QUE SE CAIGAN EN LA VIA LAS COSAS TRANSPORTADAS. ADEMAS SE INMOVILIZARA EL VEHICULO HASTA TANTO SE REMEDIE LA SITUACION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C22',0,0,15,'TRANSPORTAR CARGA DE DIMENSIONES SUPERIORES A LAS AUTORIZADAS SIN CUMPLIR CON LOS REQUISITOS EXIGIDOS. ADEMAS EL VEHICULO SERA INMOVILIZADO HASTA QUE SE REMEDIE DICHA SITUACION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C23',0,0,15,'IMPARTIR EN VIAS PUBLICAS ENSEÃ‘ANZA PRACTICA PARA CONDUCIR SIN ESTAR AUTORIZADO PARA ELLO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C24',1,0,15,'CONDUCIR MOTOCICLETA SIN OBSERVAR LAS NORMAS ESTABLECIDAS EN EL CODIGO NACIONAL DE TRANSITO TERRESTRE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C25',0,0,15,'TRANSITAR, CUANDO HUBIERE MAS DE UN CARRIL POR EL CARRIL IZQUIERDO DE LA VIA A VELOCIDAD QUE ENTORPEZCA EL TRANSITO DE LOS DEMAS VEHICULOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C26',0,0,15,'TRANSITAR EN VEHICULOS DE 3.5 O MAS TONELADAS POR EL CARRIL IZQUIERDO DE LA VIA CUANDO HUBIERE MAS DE UN CARRIL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C27',1,0,15,'CONDUCIR UN VEHICULO CUYA CARGA O PASAJEROS OBSTRUYAN LA VISIBILIDAD DEL CONDUCTOR HACIA EL FRENTE ATRAS O COSTADOS O IMPIDAN EL CONTROL SOBRE EL SISTEMA DE DIRECCION FRENOS O SEGURIDAD');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C28',0,0,15,'HACER USO DE DISPOSITIVOS PROPIOS DE VEHICULOS DE EMERGENCIA POR PARTE DE CONDUCTORES DE OTRO TIPO DE VEHICULOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C29',0,0,15,'CONDUCIR UN VEHICULO A VELOCIDAD SUPERIOR A LA MAXIMA PERMITIDA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C30',0,0,15,'NO ATENDER UNA SEÃ‘AL DE CEDA EL PASO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C31',0,0,15,'NO ACATAR LAS SEÃ‘ALES O REQUERIMIENTOS IMPARTIDOS POR LOS AGENTES DE TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION) 
VALUES ('C32',0,0,15,'NO RESPETAR EL PASO DE PEATONES QUE CRUZAN UNA VIA EN SITIO PERMITIDO PARA ELLOS O NO DARLES LA PRELACION EN LAS FRANJAS PARA ELLOS ESTABLECIDAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C33',0,0,15,'PONER UN VEHICULO EN MARCHA SIN LAS PRECAUCIONES PARA EVITAR CHOQUES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C34',0,0,15,'REPARAR UN VEHICULO EN LAS VIAS PUBLICAS PARQUE O ACERA O HACERLO EN CASO DE EMERGENCIA SIN ATENDER EL PROCEDIMIENTO SEÃ‘ALADO EN EL CODIGO NACIONAL DE TRANSITO TERRESTRE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C35',1,0,15,'NO REALIZAR LA REVISION TECNICO-MECANICA EN EL PLAZO LEGAL ESTABLECIDO O CUANDO EL VEHICULO NO SE ENCUENTRE EN ADECUADAS CONDICIONES TECNICO-MECANICAS O DE EMISION DE GASES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C36',1,0,15,'TRANSPORTAR CARGA EN CONTENEDORES SIN LOS DISPOSITIVOS ESPECIALES DE SUJECION. EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C37',0,0,15,'TRANSPORTAR PASAJEROS EN EL PLATON DE UNA CAMIONETA PICKUP O EN LA PLATAFORMA DE UN VEHICULO DE CARGA TRATESE DE FURGON O PLATAFORMA DE ESTACAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('C38',0,0,15,'USAR SISTEMAS MOVILES DE COMUNICACION O TELEFONOS INSTALADOS EN LOS VEHICULOS AL MOMENTO DE CONDUCIR EXCEPTUANDO SI ESTOS SON UTILIZADOS CON ACCESORIOS O EQUIPOS AUXILIARES QUE PERMITAN TENERLAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D01',1,0,30,'GUIAR UN VEHICULO SIN HABER OBTENIDO LA LICENCIA DE CONDUCCION CORRESPONDIENTE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D02',1,0,30,'CONDUCIR SIN PORTAR LOS SEGUROS ORDENADOS POR LA LEY. ADEMAS EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D03',1,0,30,'TRANSITAR EN SENTIDO CONTRARIO AL ESTIPULADO PARA LA VIA CALZADA O CARRIL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D04',1,0,30,'NO DETENERSE ANTE UNA LUZ ROJA O AMARILLA DE SEMAFORO UNA SEÃ‘AL DE "PARE" O UN SEMAFORO INTERMITENTE EN ROJO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D05',1,0,30,'CONDUCIR UN VEHICULO SOBRE ACERAS PLAZAS VIAS PEATONALES SEPARADORES BERMAS DEMARCACIONES DE CANALIZACION ZONAS VERDES O VIAS ESPECIALES PARA VEHICULOS NO MOTORIZADOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D06',1,0,30,'ADELANTAR A OTRO VEHICULO EN BERMA TUNEL PUENTE CURVA PASOS A NIVEL Y CRUCES NO REGULADOS O AL APROXIMARSE A LA CIMA DE UNA CUESTA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D07',1,0,30,'CONDUCIR REALIZANDO MANIOBRAS ALTAMENTE PELIGROSAS E IRRESPONSABLES QUE PONGAN EN PELIGRO A LAS PERSONAS O LAS COSAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D08',1,0,30,'CONDUCIR UN VEHICULO SIN LUCES O SIN LOS DISPOSITIVOS LUMINOSOS DE POSICION DIRECCIONALES O DE FRENO O CON ALGUNA DE ELLAS DAÃ‘ADA EN LAS HORAS O CIRCUNSTANCIAS EN QUE LO EXIGE ESTE CODIGO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D09',0,0,30,'NO PERMITIR EL PASO DE LOS VEHICULOS DE EMERGENCIA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D10',0,0,30,'CONDUCIR UN VEHICULO PARA TRANSPORTE ESCOLAR CON EXCESO DE VELOCIDAD');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D11',0,0,30,'PERMITIR EL SERVICIO PUBLICO DE PASAJEROS QUE NO TENGA LAS SALIDAS DE EMERGENCIA EXIGIDAS. EN ESTE CASO LA MULTA SE IMPONDRA SOLIDARIAMENTE A LA EMPRESA A LA CUAL ESTA AFILIADO Y AL PROPIETARIO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D12',1,0,30,'CONDUCIR UN VEHICULO QUE SIN LA DEBIDA AUTORIZACION SE DESTINE A UN SERVICIO DIFERENTE DE AQUEL PARA EL CUAL TIENE LA LICENCIA DE TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D13',1,0,30,'EN CASO DE TRANSPORTAR CARGA CON PESO SUPERIOR AL AUTORIZADO EL VEHICULO SERA INMOVILIZADO Y EL EXCESO DEBERA SER TRASBORDADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D14',1,0,30,'LAS AUTORIDADES DE TRANSITO ORDENARAN LA INMOVILIZACION INMEDIATA DE LOS VEHICULOS QUE USEN PARA SU MOVILIZACION COMBUSTIBLES NO REGULADOS COMO GAS PROPANO U OTROS QUE PONGAN EN PELIGRO LA VIDA DE LAS PERSONAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D15',1,0,30,'CAMBIO DEL RECORRIDO O TRAZADO DE LA RUTA PARA VEHICULO DE SERVICIO PUBLICO DE PASAJEROS AUTORIZADO POR EL ORGANISMO DE TRANSITO CORRESPONDIENTE');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('D17',1,0,30,'INFRACCION A LA NORMA DE EMISION CONTAMINANTE O DE GENERACION DE RUIDO POR AUTOMOTORES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('E01',0,0,45,'PROVEER COMBUSTIBLE A VEHICULOS DE SERVICIO PUBLICO CON PASAJEROS A BORDO. ADICIONALMENTE DEBERA SER SUSPENDIDA LA LICENCIA DE CONDUCCION POR UN TERMINO DE SEIS (6) MESES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('E02',0,0,45,'NEGARSE A PRESTAR EL SERVICIO PUBLICO SIN CAUSA JUSTIFICADA. SI COMO CONSECUENCIA DE LA NO PRESTACION DEL SERVICIO SE OCASIONA ALTERACION DEL ORDEN PUBLICO SE SUSPENDERA LA LICENCIA DE CONDUCCION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('E03',1,1,45,'CONDUCIR EN ESTADO DE EMBRIAGUEZ O BAJO LOS EFECTOS DE SUSTANCIAS ALUCINOGENAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('E04',1,1,45,'TRANSPORTAR EN EL MISMO VEHICULO Y AL MISMO TIEMPO PERSONAS Y SUSTANCIAS PELIGROSAS COMO EXPLOSIVOS TOXICOS RADIOACTIVOS COMBUSTIBLES NO AUTORIZADOS ETC');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F01',0,0,1,'INVADIR LA ZONA DESTINADA AL TRANSITO DE VEHICULOS TRANSITAR POR ESTA EN PATINES MONOPATINES PATINETAS O SIMILARES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F02',0,0,1,'LLEVAR SIN LAS DEBIDAS PRECAUCIONES ELEMENTOS QUE PUEDAN OBSTACULIZAR O AFECTAR EL TRANSITO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F03',0,0,1,'CRUZAR POR SITIOS NO PERMITIDOS O TRANSITAR SOBRE EL GUARDAVIAS DEL FERROCARRIL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F04',0,0,1,'COLOCARSE DELANTE O DETRAS DE UN VEHICULO QUE TENGA EL MOTOR ENCENDIDO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F05',0,0,1,'REMOLCARSE DE VEHICULOS EN MOVIMIENTO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F06',0,0,1,'ACTUAR DE MANERA QUE PONGA EN PELIGRO SU INTEGRIDAD FISICA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F07',0,0,1,'CRUZAR LA VIA ATRAVESANDO EL TRAFICO VEHICULAR EN LUGARES EN DONDE EXISTEN PASOS PEATONALES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F08',0,0,1,'OCUPAR LA ZONA DE SEGURIDAD Y PROTECCION DE LA VIA FERREA LA CUAL SE ESTABLECE A UNA DISTANCIA NO MENOR DE DOCE (12) METROS A AMBOS LADOS DEL EJE DE LA VIA FERREA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F09',0,0,1,'SUBIRSE O BAJARSE DE LOS VEHICULOS ESTANDO ESTOS EN MOVIMIENTO CUALQUIERA QUE SEA LA OPERACION O MANIOBRA QUE ESTEN REALIZANDO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F10',0,0,1,'TRANSITAR POR LOS TUNELES PUENTES Y VIADUCTOS DE LAS VIAS FERREAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F11',0,0,1,'EN RELACION CON EL STTMP ESTOS NO DEBEN OCUPAR LA ZONA DE SEGURIDAD Y CORREDORES DE TRANSITO DE LOS VEHICULOS DEL STTMP FUERA DE LOS LUGARES EXPRESAMENTE AUTORIZADOS Y HABILITADOS PARA ELLO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('F12',0,0,1,'DENTRO DEL PERIMETRO URBANO EL CRUCE DEBE HACERSE SOLO POR LAS ZONAS AUTORIZADAS COMO LOS PUENTES PEATONALES LOS PASOS PEATONALES Y LAS BOCACALLES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('G01',0,0,0,'EL PASAJERO QUE SEA SORPRENDIDO FUMANDO EN UN VEHICULO DE SERVICIO PUBLICO SERA OBLIGADO A ABANDONAR EL AUTOMOTOR Y DEBERA ASISTIR A UN CURSO DE SEGURIDAD VIAL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('G02',0,0,0,'LOS PEATONES Y CICLISTAS QUE NO CUMPLAN CON LAS DISPOSICIONES DE ESTE CODIGO SERAN AMONESTADOS POR LA AUTORIDAD DE TRANSITO COMPETENTE Y DEBERAN ASISTIR A UN CURSO FORMATIVO DICTADO POR LAS AUTORIDADES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H01',1,0,5,'CIRCULAR PORTANDO DEFENSAS RIGIDAS DIFERENTES DE LAS INSTALADAS ORIGINALMENTE POR EL FABRICANTE. ADEMAS EL VEHICULO SERA INMOVILIZADO PREVENTIVAMENTE HASTA QUE SEAN RETIRADAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H02',1,0,5,'EL CONDUCTOR QUE NO PORTE LA LICENCIA DE TRANSITO. ADEMAS EL VEHICULO SERA INMOVILIZADO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H03',0,0,5,'EL CONDUCTOR PASAJERO O PEATON QUE OBSTACULICE PERJUDIQUE O PONGA EN RIESGO A LAS DEMAS PERSONAS O QUE NO CUMPLA LAS NORMAS Y SEÃ‘ALES DE TRANSITO QUE LE SEAN APLICABLES O NO OBEDEZCA LAS INDICACIONES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H04',0,0,5,'EL CONDUCTOR QUE NO RESPETE LOS DERECHOS E INTEGRIDAD DE LOS PEATONES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H05',0,0,5,'EL CONDUCTOR QUE NO RESPETE LA PRELACION DE PASO EN INTERSECCIONES O GIROS O SEGUN LA CLASIFICACION DE LAS VIAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H06',0,0,5,'EL CONDUCTOR QUE NO TOME LAS MEDIDAS NECESARIAS PARA EVITAR EL MOVIMIENTO DE VEHICULOS ESTACIONADOS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H07',1,0,5,'EL CONDUCTOR QUE LLEVE PASAJEROS EN LA PARTE EXTERIOR DEL VEHICULO FUERA DE LA CABINA O EN LOS ESTRIBOS DE LOS MISMOS. ADEMAS EL VEHICULO SERA INMOVILIZADO PREVENTIVAMENTE HASTA QUE SE SUBSANE DICHA CONDUCTA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H08',1,0,5,'EL CONDUCTOR QUE PORTE LUCES EXPLORADORAS EN LA PARTE POSTERIOR DEL VEHICULO. ADEMAS EL VEHICULO SERA INMOVILIZADO PREVENTIVAMENTE HASTA QUE SEAN RETIRADAS');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H09',0,0,5,'EL PASAJERO QUE PROFIERA EXPRESIONES INJURIOSAS O GROSERAS PROMUEVA RIÃ‘AS O CAUSE CUALQUIER MOLESTIA A LOS DEMAS PASAJEROS. ADEMAS LA ORDEN DE ABANDONAR EL VEHICULO SIN PERJUICIO DE LAS SANCIONES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H10',0,0,5,'LOS CONDUCTORES DE VEHICULOS NO AUTOMOTORES QUE INCURRAN EN LAS SIGUIENTES INFRACCIONES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H11',0,0,5,'VIAJAR LOS MENORES DE DOS (2) AÃ‘OS SOLOS EN EL ASIENTO POSTERIOR SIN HACER USO DE UNA SILLA QUE GARANTICE SU SEGURIDAD Y QUE PERMITA SU FIJACION A EL');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H12',0,0,5,'TRANSITAR EN VEHICULOS DE ALTO TONELAJE POR LAS VIAS DE SITIOS QUE ESTEN DECLARADOS O SE DECLAREN COMO MONUMENTOS DE CONSERVACION HISTORICA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('H13',0,0,5,'LAS DEMAS CONDUCTAS QUE CONSTITUYAN INFRACCION A LAS NORMAS DE TRANSITO Y QUE NO SE ENCUENTREN DESCRITAS EN ESTE ACTO ADMINISTRATIVO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('I01',0,0,10,'EL CONDUCTOR QUE SEA SORPRENDIDO FUMANDO MIENTRAS CONDUCE DARA LUGAR A LA IMPOSICION DE DIEZ (10) SALARIOS MINIMOS LEGALES DIARIOS VIGENTES');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('I02',0,0,100,'QUIEN INCUMPLA LA OBLIGACION CONSAGRADA EN EL ARTICULO 21 DE ESTE CODIGO Y SE LE COMPRUEBE QUE EN CASO DE UN ACCIDENTE LA DEFICIENCIA DE CARACTER ORGANICO O FUNCIONAL FUE SU CAUSA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J01',0,0,90,'EL ARTICULAR U ORGANISMO ESTATAL QUE DAÃ‘E RETIRE O MODIFIQUE LAS SEÃ‘ALES U OTROS ELEMENTOS REGULADORES O INDICADORES DEL TRAFICO EN LAS CIUDADES SERA SANCIONADO CON MULTA EQUIVALENTE A TRES (3)');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J02',0,0,600,'EN CASO DE INMOVILIZACION DE VEHICULOS DE SERVICIO PUBLICO EL INCUMPLIMIENTO DEL COMPROMISO SUSCRITO POR EL PROPIETARIO O INFRACTOR DE SUBSANAR LA FALTA EN UN PLAZO NO MAYOR A CINCO (5) DIAS DARA LUGAR A UNA MULTA');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J03',0,0,1,'SERAN SANCIONADOS CON MULTA EQUIVALENE A MIL (1000) SALARIOS MINIMOS LEGALES DIARIOS VIGENTES POR CADA UNIDAD Y A LA CANCELACION DE SU REGISTRO LAS ENSAMBLADORAS O FABRICANTES DE VEHICULOS CARROCERIAS REMOLQUES SEMIRREMOLQUES Y SIMILARES QUE LOS VENDAN SIN EL RESPECTIVO MECANISMO DE IDENTIFICACION');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J04',0,0,100,'SERA SANCIONADO CON MULTA EQUIVALENTE A CIEN (100) SALARIOS MINIMOS LEGALES DIARIOS VIGENTES EL PROPIETARIO DE EXPENDIO QUE PROVEA DE COMBUSTIBLE A UN VEHICULO AUTOMOTOR DE SERVICIO PUBLICO CON EL MOTOR ENCENDIDO Y PASAJEROS A BORDO');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J05',0,0,1.5,'EL PROPIETARIO O ADMINISTRADOR DEL PARQUEADERO AUTORIZADO PARA MATERIALIZAR LA INMOVILIZACION DE UN VEHICULO QUE PERMITA SALIDA DE UN VEHICULO INMOVILIZADO POR INFRACCION A LAS NORMAS DE TRANSITO SIN ORDEN DE LA AUTORIDAD COMPETENTE INCURRIRA EN MULTA DEL SALARIO MINIMO LEGAL VIGENTE REQUERIDO. SI SE TRATA DE PARQUEADERO AUTORIZADO NO OFICIAL INCURRIRA ADEMAS EN SUSPENSION O CANCELACION DE LA AUTORIZACION DEL PATIO PARQUEADERO AUTORIZADO DE ACUERDO A LA GRAVEDAD DE LA FALTA ');
INSERT INTO TIPO_INFRACCION (CODIGO,INMOVILIZACION,SUSPENCION_LICENCIA,SALARIOS_MINIMOS,DESCRIPCION)
VALUES ('J06',0,0,600,'EL PROPIETARIO O ADMINISTRADOR DEL PARQUEADERO AUTORIZADO QUE NO ENTREGUE LOS ELEMENTOS CONTENIDOS EN EL VEHICULO Y RELACIONADOS EN EL INVENTARIO ASI COMO LAS CONDICIONES DEL ESTADO EXTERIOR DESCRITAS A SU RECIBO');

Insert into GRUA (NUMERO_GRUA,PLACA,CONSECUTIVO,DIRECCION_PATIO_ASIGNADO) values ('1','JED-323','4','CRA 6 NUMERO 56');
Insert into GRUA (NUMERO_GRUA,PLACA,CONSECUTIVO,DIRECCION_PATIO_ASIGNADO) values ('2','FJE-329','7','AV NICHOLAS CON 56');


INSERT INTO COMPARENDO (ID, FECHA, LOCALIDAD_COMUNA, VIA_PRINCIPAL, VIA_SECUNDARIA, MODALIDAD_TRANSPORTE, RADIO_ACCION, TIPO_INFRACTOR, DESCRIPCION, VEHICULO_PLACA, ESTADO, MUNICIPIO_ID, GRUA_ID, TIPO_INFRACCION_CODIGO, INFRACTOR, AGENTE) VALUES ('1', TO_DATE('2018-05-04 02:58:37', 'YYYY-MM-DD HH24:MI:SS'), 'CARACAS', 'CALLE BULEVAR C', 'CERRADA', 'MIXTO', 'MUNICIPAL', 'PASAJERO', 'NO SE', 'GRA-231','CANCELADO', '2', '1', 'H12', '1023954758', '7475129');

INSERT INTO COMPARENDO (ID, FECHA, LOCALIDAD_COMUNA, VIA_PRINCIPAL, VIA_SECUNDARIA, MODALIDAD_TRANSPORTE, RADIO_ACCION, TIPO_INFRACTOR, DESCRIPCION, VEHICULO_PLACA, ESTADO, MUNICIPIO_ID, GRUA_ID, TIPO_INFRACCION_CODIGO, INFRACTOR, AGENTE) VALUES ('2', TO_DATE('2018-05-04 02:58:37', 'YYYY-MM-DD HH24:MI:SS'), 'CARACAS', 'CALLE BULEVAR C', 'CERRADA', 'MIXTO', 'MUNICIPAL', 'PASAJERO', 'NO SE', 'GRA-231','CANCELADO', '2', '1', 'H12', '1023954758', '7475129');

Insert into DETALLE_COMPARENDO (ID,ACEPTACION_COMPATRENDO,FECHA_ASISTENCIA) values ('1','1',to_date('01/05/18','DD/MM/RR'));
Insert into DETALLE_COMPARENDO (ID,ACEPTACION_COMPATRENDO,FECHA_ASISTENCIA) values ('2','1',to_date('09/05/18','DD/MM/RR'));

Insert into CURSO (ID,DOCENTE,FECHA,HORA_INICIO,HORA_FINALIZACION) values ('1','NICOLAS DAVILA',to_date('10/05/18','DD/MM/RR'),'9','10');
Insert into CURSO (ID,DOCENTE,FECHA,HORA_INICIO,HORA_FINALIZACION) values ('2','SARA CASTANO',to_date('11/05/18','DD/MM/RR'),'7','9');

Insert into ASISTENCIA (ID,CURSO_ID) values ('1','1');
Insert into ASISTENCIA (ID,CURSO_ID) values ('2','2');

Insert into PAGO_COMPARENDO (ID,INTERESE_MORA,MONTO_TOTAL) values ('1','0','1200000');
Insert into PAGO_COMPARENDO (ID,INTERESE_MORA,MONTO_TOTAL) values ('2','0','700000');

Insert into VALORES (FECHA,VALOR_SALARIO_MINIMO,VALOR_DIA_MORA,DESCUENTO_COMPARENDO,DIAS_HABILES) values (to_date('01/05/18','DD/MM/RR'),'600000','300','5','10');
Insert into VALORES (FECHA,VALOR_SALARIO_MINIMO,VALOR_DIA_MORA,DESCUENTO_COMPARENDO,DIAS_HABILES) values (to_date('02/05/18','DD/MM/RR'),'800000','350','3','5');

Insert into INFORME_ACCIDENTE_TRANSITO (ID,TIPO_GRAVEDAD,FECHA_HORA,CLASE_ACCIDENTE,CHOQUE_CON,OBJETO_FIJO,NUMERO_MUERTOS,NUMERO_HERIDOS,AGENTE) values ('1','CON MUERTOS',to_date('09/05/18','DD/MM/RR'),'CHOQUE','TREN','ARBOL','1','1','1095489585');
Insert into INFORME_ACCIDENTE_TRANSITO (ID,TIPO_GRAVEDAD,FECHA_HORA,CLASE_ACCIDENTE,CHOQUE_CON,OBJETO_FIJO,NUMERO_MUERTOS,NUMERO_HERIDOS,AGENTE) values ('2','CON HERIDOS',to_date('10/05/18','DD/MM/RR'),'CHOQUE','VEHICULO','SEMAFORO','0','1','1095489585');

Insert into CARACTERISTICA_LUGAR (ID,AREA_ID,SECTOR_ID,ZONA_ID,DISENIO_ID,TIEMPO_ID) values ('1','URBANA','RESIDENCIAL','ESCOLAR','TRAMO DE VIA','VIENTO');
Insert into CARACTERISTICA_LUGAR (ID,AREA_ID,SECTOR_ID,ZONA_ID,DISENIO_ID,TIEMPO_ID) values ('2','RURAL','COMERCIAL','MILITAR','VIA PEATONAL','NORMAL');

Insert into LUGAR (ID,COORDENANDA_X,COORDENADA_Y,DIRECCION,LOCALIDAD_COMUNA) values ('1','567','233','CRA 45 NUMERO 56','ESPERANZA');
Insert into LUGAR (ID,COORDENANDA_X,COORDENADA_Y,DIRECCION,LOCALIDAD_COMUNA) values ('2','922','12','AVENIDA EXPRESS ','AMERICAS');

Insert into CARACTERISTICA_VIA (ID,CARAC_GEOMETRICA_VIA_1,CARAC_GEOMETRICA_VIA_2,CARAC_GEOMETRICA_VIA_3,UTILIZACION,CALZADA,CARRIL,MATERIAL,ESTADO,CONDICION,ILUMINACION,DISMINUCION_VISUAL,CONTROL_SEMAFORO,"CONTROL_SENALES",CONTROL_DEMARCACION) values ('1','RECTA','PENDIENTE','CON ACERAS','DOBLE SENTIDO','UNA','UNO','ASFALTO','BUENO','SECA','BUENA','AVISOS VALLAS','APAGADOS','PARE','LINEA DE PARE');
Insert into CARACTERISTICA_VIA (ID,CARAC_GEOMETRICA_VIA_1,CARAC_GEOMETRICA_VIA_2,CARAC_GEOMETRICA_VIA_3,UTILIZACION,CALZADA,CARRIL,MATERIAL,ESTADO,CONDICION,ILUMINACION,DISMINUCION_VISUAL,CONTROL_SEMAFORO,"CONTROL_SENALES",CONTROL_DEMARCACION) values ('2','RECTA','PENDIENTE','SIN ACERAS','UN SENTIDO','UNA','DOS','ASFALTO','MALO','SECA','MALA','AVISOS VALLAS','APAGADOS','PARE','LINEA DE PARE');

Insert into TESTIGOS (ID,INFORME_ACCIDENTE_TRANSITO_ID,TESTIMONIO,PERSONA_NIP) values ('1','1','IBA MUY RAPIDO','7475129');
Insert into TESTIGOS (ID,INFORME_ACCIDENTE_TRANSITO_ID,TESTIMONIO,PERSONA_NIP) values ('2','2','SE QUEDO DORMIDO','7475129');

Insert into VEHICULOS_AFECTADOS (ID,VEHICULO_PLACA,INMOVILIZACION,DISPOSICION,PRPIETARIO_MISMO_CONDUCTOR,INFORME_ACCIDENTE_TRANSITO_ID,FALLA_EN,LUGAR_IMPACTO,VERSION) values ('1','VLH-130','BARRIO LAS AMERICAS','MARTA LUCIA GIL','1','1','NEUMATICO','PARACHOQUES','IBA MUY RAPIDO');
Insert into VEHICULOS_AFECTADOS (ID,VEHICULO_PLACA,INMOVILIZACION,DISPOSICION,PRPIETARIO_MISMO_CONDUCTOR,INFORME_ACCIDENTE_TRANSITO_ID,FALLA_EN,LUGAR_IMPACTO,VERSION) values ('2','AXV-666','SANTANDER','LA SUEGRA','0','2','MOTOR','PUERTA IZQUIERDA','MUY DORMIDO');

Insert into PERJUDICADOS (ID,TIPO_PERJUDICADO,VEHICULOS_AFECTADOS_ID,CINTURON,CASCO,SEXO,GRAVEDAD,CONDICION,PERSONA_NIP) values ('1','PASAJERO','1','1','1','MASCULINO','HERIDO ','PASAJERO','5482637');
Insert into PERJUDICADOS (ID,TIPO_PERJUDICADO,VEHICULOS_AFECTADOS_ID,CINTURON,CASCO,SEXO,GRAVEDAD,CONDICION,PERSONA_NIP) values ('2','PASAJERO','2','1','0','FEMENINO','MUERTO','PEATON','1023954758');

Insert into EXAMEN (ID,EXAMEN_EMBRIAGUEZ,EXAMEN_DROGA,GRADO_EXAMEN_DROGA,GRADO_EXAMEN_ALCOHOL) values ('1','POSITIVO','NEGATIVO','00','77');
Insert into EXAMEN (ID,EXAMEN_EMBRIAGUEZ,EXAMEN_DROGA,GRADO_EXAMEN_DROGA,GRADO_EXAMEN_ALCOHOL) values ('2','NEGATIVO','NEGATIVO','0','0');

Insert into LICENCIA (PERSONA,NUMERO_LICENCIA,FECHA_EXPEDICION,FECHA_VENCIMIENTO,OFICINA_TRANSITO,CATEGORIA_LICENCIA) values ('1023954758','1234324',to_date('18/05/12','DD/MM/RR'),to_date('17/05/18','DD/MM/RR'),'SALENTO','C2');
Insert into LICENCIA (PERSONA,NUMERO_LICENCIA,FECHA_EXPEDICION,FECHA_VENCIMIENTO,OFICINA_TRANSITO,CATEGORIA_LICENCIA) values ('5482637','6543',to_date('17/05/12','DD/MM/RR'),to_date('22/05/26','DD/MM/RR'),'ARMENIA','A1');

Insert into POLIZA_SEGURO (N_POLIZA,FECHA_VENCIMIENTO,COMPANIA_ASEGURADORA,PLACA) values ('2342',to_date('05/05/17','DD/MM/RR'),'SOAT SEGUROS','AXV-666');
Insert into POLIZA_SEGURO (N_POLIZA,FECHA_VENCIMIENTO,COMPANIA_ASEGURADORA,PLACA) values ('66454',to_date('30/04/15','DD/MM/RR'),'TIGRE TONO','ULX-124');
--Algunas consulatas que pueden ser de ayuda.

--SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='USUARIO';
--SELECT * FROM USER_TABLES;
--SELECT * FROM USER_CONSTRAINTS;